const brawlersDatabase = {
  // --- STARTER ---
  "Shelly": { rarity: "starting", img: "assets/brawlers/shelly.png" },

  // --- RARE (9 BRAWLERS) ---
  "Nita": { rarity: "rare", img: "assets/brawlers/nita.png" },
  "Colt": { rarity: "rare", img: "assets/brawlers/colt.png" },
  "Bull": { rarity: "rare", img: "assets/brawlers/bull.png" },
  "Brock": { rarity: "rare", img: "assets/brawlers/brock.png" },
  "El Primo": { rarity: "rare", img: "assets/brawlers/el_primo.png" },
  "Barley": { rarity: "rare", img: "assets/brawlers/barley.png" },
  "Poco": { rarity: "rare", img: "assets/brawlers/poco.png" },
  "Rosa": { rarity: "rare", img: "assets/brawlers/rosa.png" },

  // --- SUPER RARE (10 BRAWLERS) ---
  "Jessie": { rarity: "super-rare", img: "assets/brawlers/jessie.png" },
  "Dynamike": { rarity: "super-rare", img: "assets/brawlers/dynamike.png" },
  "Tick": { rarity: "super-rare", img: "assets/brawlers/tick.png" },
  "8-Bit": { rarity: "super-rare", img: "assets/brawlers/8-bit.png" },
  "Rico": { rarity: "super-rare", img: "assets/brawlers/rico.png" },
  "Darryl": { rarity: "super-rare", img: "assets/brawlers/darryl.png" },
  "Penny": { rarity: "super-rare", img: "assets/brawlers/penny.png" },
  "Carl": { rarity: "super-rare", img: "assets/brawlers/carl.png" },
  "Jacky": { rarity: "super-rare", img: "assets/brawlers/jacky.png" },
  "Gus": { rarity: "super-rare", img: "assets/brawlers/gus.png" },

  // --- EPIC (32 BRAWLERS) ---
  "Bo": { rarity: "epic", img: "assets/brawlers/bo.png" },
  "Emz": { rarity: "epic", img: "assets/brawlers/emz.png" },
  "Stu": { rarity: "epic", img: "assets/brawlers/stu.png" },
  "Piper": { rarity: "epic", img: "assets/brawlers/piper.png" },
  "Pam": { rarity: "epic", img: "assets/brawlers/pam.png" },
  "Frank": { rarity: "epic", img: "assets/brawlers/frank.png" },
  "Bibi": { rarity: "epic", img: "assets/brawlers/bibi.png" },
  "Bea": { rarity: "epic", img: "assets/brawlers/bea.png" },
  "Nani": { rarity: "epic", img: "assets/brawlers/nani.png" },
  "Edgar": { rarity: "epic", img: "assets/brawlers/edgar.png" },
  "Griff": { rarity: "epic", img: "assets/brawlers/griff.png" },
  "Grom": { rarity: "epic", img: "assets/brawlers/grom.png" },
  "Bonnie": { rarity: "epic", img: "assets/brawlers/bonnie.png" },
  "Gale": { rarity: "epic", img: "assets/brawlers/gale.png" },
  "Colette": { rarity: "epic", img: "assets/brawlers/colette.png" },
  "Belle": { rarity: "epic", img: "assets/brawlers/belle.png" },
  "Ash": { rarity: "epic", img: "assets/brawlers/ash.png" },
  "Lola": { rarity: "epic", img: "assets/brawlers/lola.png" },
  "Sam": { rarity: "epic", img: "assets/brawlers/sam.png" },
  "Mandy": { rarity: "epic", img: "assets/brawlers/mandy.png" },
  "Maisie": { rarity: "epic", img: "assets/brawlers/maisie.png" },
  "Hank": { rarity: "epic", img: "assets/brawlers/hank.png" },
  "Pearl": { rarity: "epic", img: "assets/brawlers/pearl.png" },
  "Larry & Lawrie": { rarity: "epic", img: "assets/brawlers/larry_lawrie.png" },
  "Angelo": { rarity: "epic", img: "assets/brawlers/angelo.png" },
  "Berry": { rarity: "epic", img: "assets/brawlers/berry.png" },
  "Shade": { rarity: "epic", img: "assets/brawlers/shade.png" },
  "Meeple": { rarity: "epic", img: "assets/brawlers/meeple.png" },
  "Trunk": { rarity: "epic", img: "assets/brawlers/trunk.png" },
  "Lizzie": { rarity: "epic", img: "assets/brawlers/lizzie.png" },
  "Bolt": { rarity: "epic", img: "assets/brawlers/bolt.png" },
  "Pierce": { rarity: "epic", img: "assets/brawlers/pierce.png" },

  // --- MYTHIC (40 BRAWLERS) ---
  "Mortis": { rarity: "mythic", img: "assets/brawlers/mortis.png" },
  "Tara": { rarity: "mythic", img: "assets/brawlers/tara.png" },
  "Gene": { rarity: "mythic", img: "assets/brawlers/gene.png" },
  "Max": { rarity: "mythic", img: "assets/brawlers/max.png" },
  "Mr. P": { rarity: "mythic", img: "assets/brawlers/mr_p.png" },
  "Sprout": { rarity: "mythic", img: "assets/brawlers/sprout.png" },
  "Byron": { rarity: "mythic", img: "assets/brawlers/byron.png" },
  "Squeak": { rarity: "mythic", img: "assets/brawlers/squeak.png" },
  "Lou": { rarity: "mythic", img: "assets/brawlers/lou.png" },
  "Ruffs": { rarity: "mythic", img: "assets/brawlers/ruffs.png" },
  "Buzz": { rarity: "mythic", img: "assets/brawlers/buzz.png" },
  "Fang": { rarity: "mythic", img: "assets/brawlers/fang.png" },
  "Eve": { rarity: "mythic", img: "assets/brawlers/eve.png" },
  "Janet": { rarity: "mythic", img: "assets/brawlers/janet.png" },
  "Otis": { rarity: "mythic", img: "assets/brawlers/otis.png" },
  "Buster": { rarity: "mythic", img: "assets/brawlers/buster.png" },
  "Gray": { rarity: "mythic", img: "assets/brawlers/gray.png" },
  "R-T": { rarity: "mythic", img: "assets/brawlers/r-t.png" },
  "Willow": { rarity: "mythic", img: "assets/brawlers/willow.png" },
  "Doug": { rarity: "mythic", img: "assets/brawlers/doug.png" },
  "Chuck": { rarity: "mythic", img: "assets/brawlers/chuck.png" },
  "Charlie": { rarity: "mythic", img: "assets/brawlers/charlie.png" },
  "Mico": { rarity: "mythic", img: "assets/brawlers/mico.png" },
  "Melodie": { rarity: "mythic", img: "assets/brawlers/melodie.png" },
  "Lily": { rarity: "mythic", img: "assets/brawlers/lily.png" },
  "Clancy": { rarity: "mythic", img: "assets/brawlers/clancy.png" },
  "Moe": { rarity: "mythic", img: "assets/brawlers/moe.png" },
  "Juju": { rarity: "mythic", img: "assets/brawlers/juju.png" },
  "Ollie": { rarity: "mythic", img: "assets/brawlers/ollie.png" },
  "Finx": { rarity: "mythic", img: "assets/brawlers/finx.png" },
  "Lumi": { rarity: "mythic", img: "assets/brawlers/lumi.png" },
  "Jae-yong": { rarity: "mythic", img: "assets/brawlers/jae_yong.png" },
  "Alli": { rarity: "mythic", img: "assets/brawlers/alli.png" },
  "Mina": { rarity: "mythic", img: "assets/brawlers/mina.png" },
  "Ziggy": { rarity: "mythic", img: "assets/brawlers/ziggy.png" },
  "Gigi": { rarity: "mythic", img: "assets/brawlers/gigi.png" },
  "Glowbert": { rarity: "mythic", img: "assets/brawlers/glowbert.png" },
  "Najia": { rarity: "mythic", img: "assets/brawlers/najia.png" },
  "Damian": { rarity: "mythic", img: "assets/brawlers/damian.png" },
  "Wendy": { rarity: "mythic", img: "assets/brawlers/wendy.png" },

  // --- LEGENDARY (16 BRAWLERS) ---
  "Spike": { rarity: "legendary", img: "assets/brawlers/spike.png" },
  "Crow": { rarity: "legendary", img: "assets/brawlers/crow.png" },
  "Leon": { rarity: "legendary", img: "assets/brawlers/leon.png" },
  "Sandy": { rarity: "legendary", img: "assets/brawlers/sandy.png" },
  "Amber": { rarity: "legendary", img: "assets/brawlers/amber.png" },
  "Meg": { rarity: "legendary", img: "assets/brawlers/meg.png" },
  "Surge": { rarity: "legendary", img: "assets/brawlers/surge.png" },
  "Chester": { rarity: "legendary", img: "assets/brawlers/chester.png" },
  "Cordelius": { rarity: "legendary", img: "assets/brawlers/cordelius.png" },
  "Kit": { rarity: "legendary", img: "assets/brawlers/kit.png" },
  "Draco": { rarity: "legendary", img: "assets/brawlers/draco.png" },
  "Kenji": { rarity: "legendary", img: "assets/brawlers/kenji.png" },
  "Nori": { rarity: "legendary", img: "assets/brawlers/nori.png" },
  "Starr Nova": { rarity: "legendary", img: "assets/brawlers/starr_nova.png" },
  "Kaze": { rarity: "legendary", img: "assets/brawlers/kaze.png" },
  "Sirius": { rarity: "legendary", img: "assets/brawlers/sirius.png" }
};

// Freeze the database to prevent direct structural changes elsewhere in your code
Object.freeze(brawlersDatabase);
